#############################################################
# configuration file for the instalation of the herm-pic    #
# latex package.                                            #
#                                                           #
# Version: 0.1                                              #
# Author: Sven Schoradt <schoradt@informatik.tu-cottbus.de> #
#############################################################

# Tool definition

INSTALL = cp -f

LATEX = latex
DVIPS = dvips

PDFLATEX = pdflatex

# PATH definitions

# path to install the latex packages
INSTALL_PATH = ~/tex/

#path to install the documentation
DOC_PATH = ~/tex/
