#############################################################
# configuration file for the instalation of the herm-pic    #
# latex package.                                            #
#                                                           #
# Version: 0.1                                              #
# Author: Sven Schoradt <schoradt@informatik.tu-cottbus.de> #
#############################################################

# Tool definition

INSTALL = cp -f

LATEX = latex
DVIPS = dvips

PDFLATEX = pdflatex
 
# PATH definitions

INSTALL_PATH = ~/temp/tex/

DOC_PATH = ~/temp/doc/
